#
# ███╗   ███╗██████╗ ██████╗ ██╗  ██╗
# ████╗ ████║╚═══╗██╗██╔══██╗██║ ██╔╝
# ██╔████╔██║███████║██████╔╝█████╔╝
# ██║╚██╔╝██║██╔══██║██╔══██╗██╔═██╗
# ██║ ╚═╝ ██║ █████╔╝██║  ██║██║  ██╗
# ╚═╝     ╚═╝ ╚════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
# Copyright (C) 2026  Daniel Hetrick
# https://github.com/nutjob-laboratories/merk
# https://github.com/nutjob-laboratories
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

def emojize(text):

	ESCAPE_PLACEHOLDER = "\x00RAW\x00"
	ESCAPE_SEQUENCE = "\\("
	text = text.replace(ESCAPE_SEQUENCE, ESCAPE_PLACEHOLDER)

	for a in ASCIIMOIJI:
		if a in text: text = text.replace(a,ASCIIMOIJI[a])

	text = text.replace(ESCAPE_PLACEHOLDER, "(")

	return text

def demojize(text):
	for a in ASCIIMOIJI:
		if ASCIIMOIJI[a] in text: text = text.replace(ASCIIMOIJI[a],a)
	return text

ASCIIMOIJI = {'(--)': '–',
 '(->)': '→',
 '(...)': '…',
 '(007)': '┌( ͝° ͜ʖ͡°)=ε/̵͇̿̿/’̿’̿ ̿',
 '(1/2)': '½',
 '(1/3)': '⅓',
 '(1/4)': '¼',
 '(1/8)': '⅛',
 '(2/3)': '⅔',
 '(3/8)': '⅜',
 '(5)': '卌',
 '(5/8)': '⅝',
 '(7/8)': '⅞',
 '(<-)': '←',
 '(<<)': '«',
 '(>>)': '»',
 '(acid)': '⊂(◉‿◉)つ',
 '(afraid)': '(ㆆ _ ㆆ)',
 '(alpha)': 'α',
 '(angel)': '☜(⌒▽⌒)☞',
 '(angry)': '•`_´•',
 '(apple)': '\uf8ff',
 '(arrowhead)': '⤜(ⱺ ʖ̯ⱺ)⤏',
 '(ass)': '(‿|‿)',
 '(awkward)': '•͡˘㇁•͡˘',
 '(bat)': '/|\\ ^._.^ /|\\',
 '(bear)': 'ʕ·͡ᴥ·ʔ\ufeff',
 '(bearflip)': 'ʕノ•ᴥ•ʔノ ︵ ┻━┻',
 '(bearhug)': 'ʕっ•ᴥ•ʔっ',
 '(because)': '∵',
 '(bemolle)': '♭',
 '(beta)': 'β',
 '(bigheart)': '❤',
 '(blackeye)': '0__#',
 '(blubby)': '(      0    _   0    )',
 '(blush)': '(˵ ͡° ͜ʖ ͡°˵)',
 '(bond)': '┌( ͝° ͜ʖ͡°)=ε/̵͇̿̿/’̿’̿ ̿',
 '(boobs)': '( . Y . )',
 '(bored)': '(-_-)',
 '(bribe)': '( •͡˘ _•͡˘)ノð',
 '(bubbles)': '( ˘ ³˘)ノ°ﾟº❍｡',
 '(butt)': '(‿|‿)',
 '(butterfly)': 'ƸӜƷ',
 '(bye)': '(ʘ‿ʘ)╯',
 '(c)': '©',
 '(cat)': '(= ФェФ=)',
 '(catlenny)': '( ͡° ᴥ ͡°)\ufeff',
 '(check)': '✔',
 '(checkmark)': '✔',
 '(cheer)': '※\\(^o^)/※',
 '(chubby)': '╭(ʘ̆~◞౪◟~ʘ̆)╮',
 '(claro)': '(͡ ° ͜ʖ ͡ °)',
 '(clique)': 'ヽ༼ ຈل͜ຈ༼ ▀̿̿Ĺ̯̿̿▀̿ ̿༽Ɵ͆ل͜Ɵ͆ ༽ﾉ',
 '(cloud)': '☁',
 '(club)': '♣',
 '(cmd)': '⌘',
 '(coffee)': 'c[_]',
 '(command)': '⌘',
 '(cool)': '(•_•) ( •_•)>⌐■-■ (⌐■_■)',
 '(copy)': '©',
 '(copyright)': '©',
 '(creep)': 'ԅ(≖‿≖ԅ)',
 '(creepcute)': 'ƪ(ړײ)\u200eƪ\u200b\u200b',
 '(crim3s)': '( ✜︵✜ )',
 '(cross)': '†',
 '(cry)': '(╥﹏╥)',
 '(crywave)': '( ╥﹏╥) ノシ',
 '(csi)': '(•_•) ( •_•)>⌐■-■ (⌐■_■)',
 '(cuppa)': 'c[_]',
 '(cute)': '(｡◕‿‿◕｡)',
 '(d1)': '⚀',
 '(d2)': '⚁',
 '(d3)': '⚂',
 '(d4)': '⚃',
 '(d5)': '⚄',
 '(d6)': '⚅',
 '(dab)': 'ヽ( •_)ᕗ',
 '(damnyou)': '(ᕗ ͠° ਊ ͠° )ᕗ',
 '(dance)': 'ᕕ(⌐■_■)ᕗ ♪♬',
 '(dead)': 'x⸑x',
 '(dealwithit)': '(⌐■_■)',
 '(delicious)': '(っˆڡˆς)',
 '(delta)': 'Δ',
 '(depressed)': '(︶︹︶)',
 '(derp)': '☉ ‿ ⚆',
 '(diamond)': '♦',
 '(diesis)': '♯',
 '(dj)': 'd[-_-]b',
 '(do_not_want)': 'ヽ(｀Д´)ﾉ',
 '(dog)': '(◕ᴥ◕ʋ)',
 '(dollar)': '$',
 '(dong)': '(̿▀̿\u2009̿Ĺ̯̿̿▀̿ ̿)̄',
 '(donger)': 'ヽ༼ຈل͜ຈ༽ﾉ',
 '(donotwant)': 'ヽ(｀Д´)ﾉ',
 '(dontcare)': '(- ʖ̯-)',
 '(dontwant)': 'ヽ(｀Д´)ﾉ',
 '(dope)': '<(^_^)>',
 '(doubleflat)': '𝄫',
 '(doublequotesleft)': '«',
 '(doublequotesright)': '»',
 '(doublesharp)': '𝄪',
 '(doubletableflip)': '┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻',
 '(down)': '↓',
 '(duckface)': '(・3・)',
 '(duel)': 'ᕕ(╭ರ╭ ͟ʖ╮•́)⊃¤=(————-',
 '(duh)': '(≧︿≦)',
 '(dunno)': '¯\\(°_o)/¯',
 '(dunnolol)': '¯\\(°_o)/¯',
 '(dwi)': '(⌐■_■)',
 '(ebola)': 'ᴇʙᴏʟᴀ',
 '(eeriemob)': '(-(-_-(-_(-_(-_-)_-)-_-)_-)_-)-)',
 '(ellipsis)': '…',
 '(emdash)': '–',
 '(emptystar)': '☆',
 '(emptytriangle)': '△',
 '(endure)': '(҂◡_◡) ᕤ',
 '(envelope)': '✉︎',
 '(epsilon)': 'ɛ',
 '(euro)': '€',
 '(evil)': 'ψ(｀∇´)ψ',
 '(evillenny)': '(͠≖ ͜ʖ͠≖)',
 '(excited)': '(ﾉ◕ヮ◕)ﾉ*:・ﾟ✧',
 '(execution)': '(⌐■_■)︻╦╤─   (╥﹏╥)',
 '(f)': '✿',
 '(facebook)': '(╯°□°)╯︵ ʞooqǝɔɐɟ',
 '(facepalm)': '(－‸ლ)',
 '(fart)': '(ˆ⺫ˆ๑)<3',
 '(fight)': '(ง •̀_•́)ง',
 '(finn)': '| (• ◡•)|',
 '(fish)': '<"(((<3',
 '(five)': '卌',
 '(fiveeights)': '⅝',
 '(flat)': '♭',
 '(flexing)': 'ᕙ(`▽´)ᕗ',
 '(flipped)': '┬─┬\ufeff ︵ /(.□. \\）',
 '(flor)': '(✿◠‿◠)',
 '(flower)': '(✿◠‿◠)',
 '(flower2)': '✿',
 '(fly)': '─=≡Σ((( つ◕ل͜◕)つ',
 '(friendflip)': '(╯°□°)╯︵ ┻━┻ ︵ ╯(°□° ╯)',
 '(frown)': '(ღ˘⌣˘ღ)',
 '(fu)': '┌П┐(ಠ_ಠ)',
 '(fuckoff)': '୧༼ಠ益ಠ╭∩╮༽',
 '(fuckyou)': '┌П┐(ಠ_ಠ)',
 '(gang)': 'ヽ༼ ຈل͜ຈ༼ ▀̿̿Ĺ̯̿̿▀̿ ̿༽Ɵ͆ل͜Ɵ͆ ༽ﾉ',
 '(gentleman)': 'ಠ_ರೃ',
 '(ghast)': '= _ =',
 '(ghost)': '༼ つ ╹ ╹ ༽つ',
 '(gift)': '(´・ω・)っ由',
 '(gimme)': '༼ つ ◕_◕ ༽つ',
 '(givemeyourmoney)': '(•-•)⌐',
 '(glasses)': '(⌐ ͡■ ͜ʖ ͡■)',
 '(glassesoff)': '( ͡° ͜ʖ ͡°)ﾉ⌐■-■',
 '(glitter)': '(*・‿・)ノ⌒*:･ﾟ✧',
 '(glitterbomb)': '(*・‿・)ノ⌒*:･ﾟ✧',
 '(glitterderp)': '(ﾉ☉ヮ⚆)ﾉ ⌒*:･ﾟ✧',
 '(gloomy)': '(_゜_゜_)',
 '(goatse)': '(з๏ε)',
 '(gotit)': '(☞ﾟ∀ﾟ)☞',
 '(greet)': '( ´◔ ω◔`) ノシ',
 '(greetings)': '( ´◔ ω◔`) ノシ',
 '(gtfo)': '୧༼ಠ益ಠ╭∩╮༽',
 '(gun)': '︻╦╤─',
 '(h)': '♥',
 '(hadouken)': '༼つಠ益ಠ༽つ ─=≡ΣO))',
 '(haha)': '٩(^‿^)۶',
 '(hammerandsickle)': '☭',
 '(handleft)': '☜',
 '(handright)': '☞',
 '(happy)': '٩( ๑╹ ꇴ╹)۶',
 '(happygarry)': 'ᕕ( ᐛ )ᕗ',
 '(heart)': '♥',
 '(heavytable)': '┬─┬\ufeff ︵ /(.□. \\）',
 '(hello)': '(ʘ‿ʘ)╯',
 '(help)': '\\(°Ω°)/',
 '(highfive)': '._.)/\\(._.',
 '(hitting)': '( ｀皿´)｡ﾐ/',
 '(hl)': '☜',
 '(hr)': '☞',
 '(hs)': '☭',
 '(hug)': '(づ｡◕‿‿◕｡)づ',
 '(hugs)': '(づ｡◕‿‿◕｡)づ',
 '(idc)': '(- ʖ̯-)',
 '(iknowright)': '┐｜･ิω･ิ#｜┌',
 '(ikr)': '┐｜･ิω･ิ#｜┌',
 '(illuminati)': '୧(▲ᴗ▲)ノ',
 '(inf)': '∞',
 '(infinity)': '∞',
 '(inject)': '┌(◉ ͜ʖ◉)つ┣▇▇▇═──',
 '(inlove)': '(っ´ω`c)♡',
 '(int)': '∫',
 '(integral)': '∫',
 '(internet)': 'ଘ(੭*ˊᵕˋ)੭*\u200àˋ ɪɴᴛᴇʀɴᴇᴛ',
 '(interrobang)': '‽',
 '(jake)': '(❍ᴥ❍ʋ)',
 '(kappa)': '(¬,‿,¬)',
 '(kawaii)': '≧◡≦',
 '(keen)': '┬┴┬┴┤Ɵ͆ل͜Ɵ͆ ༽ﾉ',
 '(kiahh)': '~\\(≧▽≦)/~',
 '(kiss)': '(づ ￣ ³￣)づ',
 '(koala)': 'ʕ·͡ᴥ·ʔ\ufeff',
 '(kyubey)': '／人◕ ‿‿ ◕人＼',
 '(lambda)': 'λ',
 '(lazy)': '_(:3」∠)_',
 '(left)': '←',
 '(lenny)': '( ͡° ͜ʖ ͡°)',
 '(lennybill)': '[̲̅$̲̅(̲̅ ͡° ͜ʖ ͡°̲̅)̲̅$̲̅]',
 '(lennyfight)': '(ง ͠° ͟ʖ ͡°)ง',
 '(lennyflip)': '(ノ ͡° ͜ʖ ͡°ノ)   ︵ ( ͜。 ͡ʖ ͜。)',
 '(lennygang)': '( ͡°( ͡° ͜ʖ( ͡° ͜ʖ ͡°)ʖ ͡°) ͡°)',
 '(lennyshrug)': '¯\\_( ͡° ͜ʖ ͡°)_/¯',
 '(lennysir)': '( ಠ ͜ʖ ರೃ)',
 '(lennystalker)': '┬┴┬┴┤( ͡° ͜ʖ├┬┴┬┴',
 '(lennystrong)': 'ᕦ( ͡° ͜ʖ ͡°)ᕤ',
 '(lennywizard)': '╰( ͡° ͜ʖ ͡° )つ──☆*:・ﾟ',
 '(letter)': '✉︎',
 '(lol)': 'L(° O °L)',
 '(look)': '(ಡ_ಡ)☞',
 '(loud)': 'ᕦ(⩾﹏⩽)ᕥ',
 '(love)': '♥‿♥',
 '(lovebear)': 'ʕ♥ᴥ♥ʔ',
 '(lumpy)': '꒰ ꒡⌓꒡꒱',
 '(luv)': '-`ღ´-',
 '(mad)': 't(ಠ益ಠt)',
 '(magic)': 'ヽ(｀Д´)⊃━☆ﾟ. * ･ ｡ﾟ,',
 '(magicflip)': '(/¯◡ ‿ ◡)/¯ ~ ┻━┻',
 '(meditation)': '⊹╰(⌣ʟ⌣)╯⊹',
 '(meep)': '\\(°^°)/',
 '(meh)': 'ಠ_ಠ',
 '(metal)': '\\m/,(> . <)_\\m/',
 '(mg)': '︻╦╤─',
 '(mistyeyes)': 'ಡ_ಡ',
 '(monocle)': 'ಠ_ರೃ',
 '(monster)': '༼ ༎ຶ ෴ ༎ຶ༽',
 '(natural)': '♮',
 '(needle)': '┌(◉ ͜ʖ◉)つ┣▇▇▇═──',
 '(nerd)': '(⌐⊙_⊙)',
 '(nice)': '( ͡° ͜ °)',
 '(no)': '→_←',
 '(noclue)': '／人◕ __ ◕人＼',
 '(noise)': 'ᕦ(⩾﹏⩽)ᕥ',
 '(nom)': '(っˆڡˆς)',
 '(note)': '♫',
 '(nuclear)': '☢',
 '(nukular)': '☢',
 '(nyan)': '~=[,,_,,]:3',
 '(nyeh)': '@^@',
 '(ohai)': '(ʘ‿ʘ)╯',
 '(ohreally)': '(눈_눈)',
 '(ohshit)': '( º﹃º )',
 '(ohyou)': '(◞థ౪థ)ᴖ',
 '(omega)': 'Ω',
 '(omg)': '◕_◕',
 '(omm)': '⊹╰(⌣ʟ⌣)╯⊹',
 '(oneeighth)': '⅛',
 '(onefourth)': '¼',
 '(onehalf)': '½',
 '(onethird)': '⅓',
 '(opt)': '⌥',
 '(option)': '⌥',
 '(orly)': '(눈_눈)',
 '(ou)': '(◞థ౪థ)ᴖ',
 '(peace)': '✌(-‿-)✌',
 '(pear)': '(__>-',
 '(pi)': 'π',
 '(pingpong)': '( •_•)O*¯`·.¸.·´¯`°Q(•_• )',
 '(plain)': '._.',
 '(pleased)': '(˶‾᷄ ⁻̫ ‾᷅˵)',
 '(point)': '(☞ﾟヮﾟ)☞',
 '(pooh)': 'ʕ •́؈•̀)',
 '(porcupine)': "(•ᴥ• )́`́'́`́'́⻍",
 '(pound)': '£',
 '(praise)': '(☝ ՞ਊ ՞)☝',
 '(present)': '(´・ω・)っ由',
 '(punch)': "O=('-'Q)",
 '(r)': '®',
 '(radioactive)': '☢',
 '(rage)': 't(ಠ益ಠt)',
 '(rageflip)': '(ノಠ益ಠ)ノ彡┻━┻',
 '(rainbowcat)': '(=^･ｪ･^=))ﾉ彡☆',
 '(really)': 'ò_ô',
 '(registered)': '®',
 '(right)': '→',
 '(riot)': '୧༼ಠ益ಠ༽୨',
 '(rock)': '\\m/,(> . <)_\\m/',
 '(rolleyes)': '(◔_◔)',
 '(rose)': '✿ڿڰۣ—',
 '(run)': '(╯°□°)╯',
 '(sad)': 'ε(´סּ︵סּ`)з',
 '(saddonger)': 'ヽ༼ຈʖ̯ຈ༽ﾉ',
 '(sadlenny)': '( ͡° ʖ̯ ͡°)',
 '(seveneigths)': '⅞',
 '(sharp)': '♯',
 '(shout)': '╚(•⌂•)╝',
 '(shrug)': '¯\\_(ツ)_/¯',
 '(shy)': '=^_^=',
 '(sigma)': 'Σ',
 '(since)': '∵',
 '(sing)': '♫',
 '(sir)': 'ಠ_ರೃ',
 '(skull)': '☠',
 '(smile)': 'ツ',
 '(smiley)': '☺︎',
 '(smirk)': '¬‿¬',
 '(snowman)': '☃',
 '(so)': '⸫',
 '(sob)': '(;´༎ຶД༎ຶ`)',
 '(soviettableflip)': 'ノ┬─┬ノ ︵ ( \\o°o)\\',
 '(spade)': '♠',
 '(sqrt)': '√',
 '(squad)': 'ヽ༼ ຈل͜ຈ༼ ▀̿̿Ĺ̯̿̿▀̿ ̿༽Ɵ͆ل͜Ɵ͆ ༽ﾉ',
 '(squareroot)': '√',
 '(squid)': '<コ:彡',
 '(stalker)': '┬┴┬┴┤(･_├┬┴┬┴',
 '(star)': '★',
 '(strong)': 'ᕙ(⇀‸↼‶)ᕗ',
 '(suicide)': 'ε/̵͇̿̿/’̿’̿ ̿(◡︵◡)',
 '(sum)': '∑',
 '(sun)': '☀',
 '(surprised)': '(๑•́ ヮ •̀๑)',
 '(surrender)': '\\_(-_-)_/',
 '(swag)': '(̿▀̿‿\u2009̿▀̿ ̿)',
 '(sword)': 'o()xxxx[{::::::::::::::::::>',
 '(t)': '▲',
 '(t2)': '△',
 '(tabledown)': '┬─┬\ufeff ノ( ゜-゜ノ)',
 '(tableflip)': '(ノ ゜Д゜)ノ ︵ ┻━┻',
 '(tau)': 'τ',
 '(tears)': '(ಥ﹏ಥ)',
 '(terrorist)': '୧༼ಠ益ಠ༽︻╦╤─',
 '(thanks)': '\\(^-^)/',
 '(thankyou)': '\\(^-^)/',
 '(therefore)': '⸫',
 '(this)': '( ͡° ͜ʖ ͡°)_/¯',
 '(thisis)': '( ͡° ͜ʖ ͡°)_/¯',
 '(threeeights)': '⅜',
 '(tiefighter)': '|=-(¤)-=|',
 '(tired)': '(=____=)',
 '(tm)': '™',
 '(toldyou)': '☜(꒡⌓꒡)',
 '(toldyouso)': '☜(꒡⌓꒡)',
 '(toogood)': 'ᕦ(òᴥó)ᕥ',
 '(trademark)': '™',
 '(triangle)': '▲',
 '(twothirds)': '⅔',
 '(ty)': '\\(^-^)/',
 '(ukids)': 'ლ༼>╭ ͟ʖ╮<༽ლ',
 '(unflip)': '┬──┬ ノ(ò_óノ)',
 '(up)': '↑',
 '(victory)': '(๑•̀ㅂ•́)ง✧',
 '(wat)': '(ÒДÓױ)',
 '(wave)': '( * ^ *) ノシ',
 '(whaa)': 'Ö',
 '(whistle)': '(っ^з^)♪♬',
 '(whoa)': '(°o•)',
 '(why)': 'ლ(`◉◞౪◟◉‵ლ)',
 '(woo)': '＼(＾O＾)／',
 '(wtf)': "(⊙＿⊙')",
 '(wut)': '⊙ω⊙',
 '(y_u_no)': 'u no (屮ﾟДﾟ)屮 Y U NO',
 '(y)': 'u no (屮ﾟДﾟ)屮 Y U NO',
 '(yay)': '\\( ﾟヮﾟ)/',
 '(yeah)': '(•̀ᴗ•́)و ̑̑',
 '(yen)': '¥',
 '(yes)': '(•̀ᴗ•́)و ̑̑',
 '(yinyang)': '☯',
 '(yolo)': 'Yᵒᵘ Oᶰˡʸ Lᶤᵛᵉ Oᶰᶜᵉ',
 '(youkids)': 'ლ༼>╭ ͟ʖ╮<༽ლ',
 '(yummy)': '(っˆڡˆς)',
 '(yuno)': 'u no (屮ﾟДﾟ)屮 Y U NO',
 '(yy)': '☯',
 '(zen)': '⊹╰(⌣ʟ⌣)╯⊹',
 '(zoidberg)': '(V) (°,,,,°) (V)',
 '(zombie)': '[¬º-°]¬'}