#
# ███╗   ███╗██████╗ ██████╗ ██╗  ██╗
# ████╗ ████║╚═══╗██╗██╔══██╗██║ ██╔╝
# ██╔████╔██║███████║██████╔╝█████╔╝
# ██║╚██╔╝██║██╔══██║██╔══██╗██╔═██╗
# ██║ ╚═╝ ██║ █████╔╝██║  ██║██║  ██╗
# ╚═╝     ╚═╝ ╚════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
# Copyright (C) 2025  Daniel Hetrick
# https://github.com/nutjob-laboratories/merk
# https://github.com/nutjob-laboratories
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

EMOJI_AUTOCOMPLETE_DATA=""":ab:
:ab_button_blood_type:
:atm:
:atm_sign:
:a:
:a_button_blood_type:
:a:
:a_button_blood_type:
:flag_for_Afghanistan:
:afghanistan:
:flag_for_Albania:
:albania:
:flag_for_Algeria:
:algeria:
:flag_for_American_Samoa:
:american_samoa:
:flag_for_Andorra:
:andorra:
:flag_for_Angola:
:angola:
:flag_for_Anguilla:
:anguilla:
:flag_for_Antarctica:
:antarctica:
:flag_for_Antigua_&_Barbuda:
:antigua_barbuda:
:aquarius:
:flag_for_Argentina:
:argentina:
:aries:
:flag_for_Armenia:
:armenia:
:flag_for_Aruba:
:aruba:
:flag_for_Ascension_Island:
:ascension_island:
:flag_for_Australia:
:australia:
:flag_for_Austria:
:austria:
:flag_for_Azerbaijan:
:azerbaijan:
:back:
:back_arrow:
:b:
:b_button_blood_type:
:b:
:b_button_blood_type:
:flag_for_Bahamas:
:bahamas:
:flag_for_Bahrain:
:bahrain:
:flag_for_Bangladesh:
:bangladesh:
:flag_for_Barbados:
:barbados:
:flag_for_Belarus:
:belarus:
:flag_for_Belgium:
:belgium:
:flag_for_Belize:
:belize:
:flag_for_Benin:
:benin:
:flag_for_Bermuda:
:bermuda:
:flag_for_Bhutan:
:bhutan:
:flag_for_Bolivia:
:bolivia:
:flag_for_Bosnia_&_Herzegovina:
:bosnia_herzegovina:
:flag_for_Botswana:
:botswana:
:flag_for_Bouvet_Island:
:bouvet_island:
:flag_for_Brazil:
:brazil:
:flag_for_British_Indian_Ocean_Territory:
:british_indian_ocean_territory:
:flag_for_British_Virgin_Islands:
:british_virgin_islands:
:flag_for_Brunei:
:brunei:
:flag_for_Bulgaria:
:bulgaria:
:flag_for_Burkina_Faso:
:burkina_faso:
:flag_for_Burundi:
:burundi:
:cl:
:cl_button:
:cool:
:cool_button:
:flag_for_Cambodia:
:cambodia:
:flag_for_Cameroon:
:cameroon:
:flag_for_Canada:
:canada:
:flag_for_Canary_Islands:
:canary_islands:
:cancer:
:flag_for_Cape_Verde:
:cape_verde:
:capricorn:
:flag_for_Caribbean_Netherlands:
:caribbean_netherlands:
:flag_for_Cayman_Islands:
:cayman_islands:
:flag_for_Central_African_Republic:
:central_african_republic:
:flag_for_Ceuta_&_Melilla:
:ceuta_melilla:
:flag_for_Chad:
:chad:
:flag_for_Chile:
:chile:
:flag_for_China:
:cn:
:flag_for_Christmas_Island:
:christmas_island:
:christmas_tree:
:flag_for_Clipperton_Island:
:clipperton_island:
:flag_for_Cocos_Islands:
:cocos_islands:
:flag_for_Colombia:
:colombia:
:flag_for_Comoros:
:comoros:
:flag_for_Congo_Brazzaville:
:congo_brazzaville:
:flag_for_Congo_Kinshasa:
:congo_kinshasa:
:flag_for_Cook_Islands:
:cook_islands:
:flag_for_Costa_Rica:
:costa_rica:
:flag_for_Croatia:
:croatia:
:flag_for_Cuba:
:cuba:
:flag_for_Curaçao:
:curacao:
:flag_for_Cyprus:
:cyprus:
:flag_for_Czech_Republic:
:czech_republic:
:flag_for_Côte_d’Ivoire:
:cote_divoire:
:flag_for_Denmark:
:denmark:
:flag_for_Diego_Garcia:
:diego_garcia:
:flag_for_Djibouti:
:djibouti:
:flag_for_Dominica:
:dominica:
:flag_for_Dominican_Republic:
:dominican_republic:
:end:
:end_arrow:
:flag_for_Ecuador:
:ecuador:
:flag_for_Egypt:
:egypt:
:flag_for_El_Salvador:
:el_salvador:
:england:
:flag_for_Equatorial_Guinea:
:equatorial_guinea:
:flag_for_Eritrea:
:eritrea:
:flag_for_Estonia:
:estonia:
:flag_for_Swaziland:
:swaziland:
:flag_for_Ethiopia:
:ethiopia:
:flag_for_European_Union:
:eu:
:european_union:
:free:
:free_button:
:flag_for_Falkland_Islands:
:falkland_islands:
:flag_for_Faroe_Islands:
:faroe_islands:
:flag_for_Fiji:
:fiji:
:flag_for_Finland:
:finland:
:flag_for_France:
:fr:
:flag_for_French_Guiana:
:french_guiana:
:flag_for_French_Polynesia:
:french_polynesia:
:flag_for_French_Southern_Territories:
:french_southern_territories:
:flag_for_Gabon:
:gabon:
:flag_for_Gambia:
:gambia:
:gemini:
:flag_for_Georgia:
:georgia:
:flag_for_Germany:
:de:
:flag_for_Ghana:
:ghana:
:flag_for_Gibraltar:
:gibraltar:
:flag_for_Greece:
:greece:
:flag_for_Greenland:
:greenland:
:flag_for_Grenada:
:grenada:
:flag_for_Guadeloupe:
:guadeloupe:
:flag_for_Guam:
:guam:
:flag_for_Guatemala:
:guatemala:
:flag_for_Guernsey:
:guernsey:
:flag_for_Guinea:
:guinea:
:flag_for_Guinea_Bissau:
:guinea_bissau:
:flag_for_Guyana:
:guyana:
:flag_for_Haiti:
:haiti:
:flag_for_Heard_&_McDonald_Islands:
:heard_mcdonald_islands:
:flag_for_Honduras:
:honduras:
:flag_for_Hong_Kong:
:hong_kong:
:flag_for_Hungary:
:hungary:
:id:
:id_button:
:flag_for_Iceland:
:iceland:
:flag_for_India:
:india:
:flag_for_Indonesia:
:indonesia:
:flag_for_Iran:
:iran:
:flag_for_Iraq:
:iraq:
:flag_for_Ireland:
:ireland:
:flag_for_Isle_of_Man:
:isle_of_man:
:flag_for_Israel:
:israel:
:flag_for_Italy:
:it:
:flag_for_Jamaica:
:jamaica:
:flag_for_Japan:
:jp:
:accept:
:japanese_acceptable_button:
:u7533:
:japanese_application_button:
:ideograph_advantage:
:japanese_bargain_button:
:japanese_castle:
:congratulations:
:japanese_congratulations_button:
:congratulations:
:japanese_congratulations_button:
:u5272:
:japanese_discount_button:
:dolls:
:japanese_dolls:
:u7121:
:japanese_free_of_charge_button:
:koko:
:japanese_here_button:
:u6708:
:japanese_monthly_amount_button:
:u6708:
:japanese_monthly_amount_button:
:u6e80:
:japanese_no_vacancy_button:
:u6709:
:japanese_not_free_of_charge_button:
:u55b6:
:japanese_open_for_business_button:
:u5408:
:japanese_passing_grade_button:
:post_office:
:japanese_post_office:
:u7981:
:japanese_prohibited_button:
:u6307:
:japanese_reserved_button:
:secret:
:japanese_secret_button:
:secret:
:japanese_secret_button:
:sa:
:japanese_service_charge_button:
:sa:
:japanese_service_charge_button:
:beginner:
:japanese_symbol_for_beginner:
:u7a7a:
:japanese_vacancy_button:
:flag_for_Jersey:
:jersey:
:flag_for_Jordan:
:jordan:
:flag_for_Kazakhstan:
:kazakhstan:
:flag_for_Kenya:
:kenya:
:flag_for_Kiribati:
:kiribati:
:flag_for_Kosovo:
:kosovo:
:flag_for_Kuwait:
:kuwait:
:flag_for_Kyrgyzstan:
:kyrgyzstan:
:flag_for_Laos:
:laos:
:flag_for_Latvia:
:latvia:
:flag_for_Lebanon:
:lebanon:
:leo:
:flag_for_Lesotho:
:lesotho:
:flag_for_Liberia:
:liberia:
:libra:
:flag_for_Libya:
:libya:
:flag_for_Liechtenstein:
:liechtenstein:
:flag_for_Lithuania:
:lithuania:
:flag_for_Luxembourg:
:luxembourg:
:flag_for_Macau:
:macau:
:flag_for_Madagascar:
:madagascar:
:flag_for_Malawi:
:malawi:
:flag_for_Malaysia:
:malaysia:
:flag_for_Maldives:
:maldives:
:flag_for_Mali:
:mali:
:flag_for_Malta:
:malta:
:flag_for_Marshall_Islands:
:marshall_islands:
:flag_for_Martinique:
:martinique:
:flag_for_Mauritania:
:mauritania:
:flag_for_Mauritius:
:mauritius:
:flag_for_Mayotte:
:mayotte:
:flag_for_Mexico:
:mexico:
:flag_for_Micronesia:
:micronesia:
:flag_for_Moldova:
:moldova:
:flag_for_Monaco:
:monaco:
:flag_for_Mongolia:
:mongolia:
:flag_for_Montenegro:
:montenegro:
:flag_for_Montserrat:
:montserrat:
:flag_for_Morocco:
:morocco:
:flag_for_Mozambique:
:mozambique:
:mrs_claus:
:mx_claus:
:flag_for_Myanmar:
:myanmar:
:new:
:new_button:
:ng:
:ng_button:
:flag_for_Namibia:
:namibia:
:flag_for_Nauru:
:nauru:
:flag_for_Nepal:
:nepal:
:flag_for_Netherlands:
:netherlands:
:flag_for_New_Caledonia:
:new_caledonia:
:flag_for_New_Zealand:
:new_zealand:
:flag_for_Nicaragua:
:nicaragua:
:flag_for_Niger:
:niger:
:flag_for_Nigeria:
:nigeria:
:flag_for_Niue:
:niue:
:flag_for_Norfolk_Island:
:norfolk_island:
:flag_for_North_Korea:
:north_korea:
:flag_for_Macedonia:
:macedonia:
:flag_for_Northern_Mariana_Islands:
:northern_mariana_islands:
:flag_for_Norway:
:norway:
:ok:
:ok_button:
:ok_hand:
:on:
:on_arrow:
:on!_arrow:
:o2:
:o_button_blood_type:
:o2:
:o_button_blood_type:
:flag_for_Oman:
:oman:
:ophiuchus:
:parking:
:p_button:
:parking:
:p_button:
:flag_for_Pakistan:
:pakistan:
:flag_for_Palau:
:palau:
:flag_for_Palestinian_Territories:
:palestinian_territories:
:flag_for_Panama:
:panama:
:flag_for_Papua_New_Guinea:
:papua_new_guinea:
:flag_for_Paraguay:
:paraguay:
:flag_for_Peru:
:peru:
:flag_for_Philippines:
:philippines:
:pisces:
:flag_for_Pitcairn_Islands:
:pitcairn_islands:
:flag_for_Poland:
:poland:
:flag_for_Portugal:
:portugal:
:flag_for_Puerto_Rico:
:puerto_rico:
:flag_for_Qatar:
:qatar:
:flag_for_Romania:
:romania:
:flag_for_Russia:
:ru:
:flag_for_Rwanda:
:rwanda:
:flag_for_Réunion:
:reunion:
:soon:
:soon_arrow:
:sos:
:sos_button:
:sagittarius:
:flag_for_Samoa:
:samoa:
:flag_for_San_Marino:
:san_marino:
:santa:
:santa_claus:
:flag_for_Sark:
:flag_for_Saudi_Arabia:
:saudi_arabia:
:scorpius:
:scorpio:
:scotland:
:flag_for_Senegal:
:senegal:
:flag_for_Serbia:
:serbia:
:flag_for_Seychelles:
:seychelles:
:flag_for_Sierra_Leone:
:sierra_leone:
:flag_for_Singapore:
:singapore:
:flag_for_Sint_Maarten:
:sint_maarten:
:flag_for_Slovakia:
:slovakia:
:flag_for_Slovenia:
:slovenia:
:flag_for_Solomon_Islands:
:solomon_islands:
:flag_for_Somalia:
:somalia:
:flag_for_South_Africa:
:south_africa:
:flag_for_South_Georgia_&_South_Sandwich_Islands:
:south_georgia_south_sandwich_islands:
:flag_for_South_Korea:
:kr:
:flag_for_South_Sudan:
:south_sudan:
:flag_for_Spain:
:es:
:flag_for_Sri_Lanka:
:sri_lanka:
:flag_for_St._Barthélemy:
:st_barthelemy:
:flag_for_St._Helena:
:st_helena:
:flag_for_St._Kitts_&_Nevis:
:st_kitts_nevis:
:flag_for_St._Lucia:
:st_lucia:
:flag_for_St._Martin:
:st_martin:
:flag_for_St._Pierre_&_Miquelon:
:st_pierre_miquelon:
:flag_for_St._Vincent_&_Grenadines:
:st_vincent_grenadines:
:statue_of_liberty:
:flag_for_Sudan:
:sudan:
:flag_for_Suriname:
:suriname:
:flag_for_Svalbard_&_Jan_Mayen:
:svalbard_jan_mayen:
:flag_for_Sweden:
:sweden:
:flag_for_Switzerland:
:switzerland:
:flag_for_Syria:
:syria:
:flag_for_São_Tomé_&_Príncipe:
:sao_tome_principe:
:t-rex:
:t_rex:
:top:
:top_arrow:
:flag_for_Taiwan:
:taiwan:
:flag_for_Tajikistan:
:tajikistan:
:flag_for_Tanzania:
:tanzania:
:taurus:
:flag_for_Thailand:
:thailand:
:flag_for_Timor_Leste:
:timor_leste:
:flag_for_Togo:
:togo:
:flag_for_Tokelau:
:tokelau:
:tokyo_tower:
:flag_for_Tonga:
:tonga:
:flag_for_Trinidad_&_Tobago:
:trinidad_tobago:
:flag_for_Tristan_da_Cunha:
:tristan_da_cunha:
:flag_for_Tunisia:
:tunisia:
:flag_for_Turkmenistan:
:turkmenistan:
:flag_for_Turks_&_Caicos_Islands:
:turks_caicos_islands:
:flag_for_Tuvalu:
:tuvalu:
:flag_for_Turkey:
:Turkey:
:tr:
:flag_for_U.S._Outlying_Islands:
:us_outlying_islands:
:flag_for_U.S._Virgin_Islands:
:us_virgin_islands:
:up:
:up_button:
:flag_for_Uganda:
:uganda:
:flag_for_Ukraine:
:ukraine:
:flag_for_United_Arab_Emirates:
:united_arab_emirates:
:flag_for_United_Kingdom:
:gb:
:uk:
:united_nations:
:flag_for_United_States:
:us:
:flag_for_Uruguay:
:uruguay:
:flag_for_Uzbekistan:
:uzbekistan:
:vs:
:vs_button:
:flag_for_Vanuatu:
:vanuatu:
:flag_for_Vatican_City:
:vatican_city:
:flag_for_Venezuela:
:venezuela:
:flag_for_Vietnam:
:vietnam:
:virgo:
:wales:
:flag_for_Wallis_&_Futuna:
:wallis_futuna:
:flag_for_Western_Sahara:
:western_sahara:
:flag_for_Yemen:
:yemen:
:zzz:
:flag_for_Zambia:
:zambia:
:flag_for_Zimbabwe:
:zimbabwe:
:tickets:
:tickets:
:airplane_arriving:
:flight_arrival:
:flight_departure:
:space_invader:
:football:
:anger:
:angry:
:imp:
:anguished:
:signal_strength:
:cold_sweat:
:art:
:astonished:
:car:
:red_car:
:angel:
:point_down:
:point_left:
:point_right:
:point_up_2:
:school_satchel:
:badminton_racquet_and_shuttlecock:
:scales:
:scales:
:ballot_box:
:ballot_box:
:barber:
:beach_umbrella:
:beach_umbrella:
:grin:
:heartbeat:
:beer:
:no_bell:
:bento:
:bike:
:biohazard_sign:
:biohazard_sign:
:birthday:
:raven:
:crow:
:rook:
:waving_black_flag:
:black_medium_small_square:
:large_blue_circle:
:champagne:
:breast_feeding:
:bricks:
:swim_brief:
:high_brightness:
:bullettrain_front:
:dart:
:busstop:
:date:
:dromedary_camel:
:camera_flash:
:flags:
:european_castle:
:cat2:
:cat:
:joy_cat:
:smirk_cat:
:chart_with_downwards_trend:
:chart_with_upwards_trend:
:chart:
:ballot_box_with_check:
:ballot_box_with_check:
:heavy_check_mark:
:heavy_check_mark:
:white_check_mark:
:cheese:
:checkered_flag:
:smoking:
:m:
:circled_m:
:m:
:circled_m:
:city_sunset:
:compression:
:compression:
:clapper:
:clap:
:beers:
:arrows_clockwise:
:mailbox_closed:
:mailbox:
:thunder_cloud_and_rain:
:thunder_cloud_and_rain:
:clubs:
:clubs:
:pouch:
:cocktail:
:boom:
:minidisc:
:three_button_mouse:
:three_button_mouse:
:confounded:
:confused:
:rice:
:egg:
:fried_egg:
:arrows_counterclockwise:
:cow2:
:cow:
:lower_left_crayon:
:lower_left_crayon:
:cricket_bat_and_ball:
:x:
:negative_squared_cross_mark:
:crying_cat_face:
:cry:
:curry:
:dagger_knife:
:dagger_knife:
:emoji_modifier_fitzpatrick_type_6:
:dash:
:truck:
:derelict_house_building:
:derelict_house_building:
:sleuth_or_spy:
:sleuth_or_spy:
:diamonds:
:diamonds:
:diamond_shape_with_a_dot_inside:
:low_brightness:
:disappointed:
:heavy_division_sign:
:dog2:
:dog:
:dollar:
:flipper:
:six_pointed_star:
:dotted_six_pointed_star:
:loop:
:bangbang:
:bangbang:
:dove_of_peace:
:dove_of_peace:
:arrow_lower_left:
:down_left_arrow:
:arrow_lower_left:
:down_left_arrow:
:arrow_lower_right:
:down_right_arrow:
:arrow_lower_right:
:down_right_arrow:
:arrow_down:
:arrow_down:
:sweat:
:arrow_down_small:
:email:
:e_mail:
:corn:
:egg2:
:eight_pointed_black_star:
:eight_pointed_star:
:eight_pointed_black_star:
:eight_pointed_star:
:eight_spoked_asterisk:
:eight_spoked_asterisk:
:clock830:
:eight_thirty:
:clock8:
:eight_oclock:
:eject_symbol:
:eject_symbol:
:clock1130:
:eleven_thirty:
:clock11:
:eleven_oclock:
:rage:
:pout:
:euro:
:sheep:
:interrobang:
:interrobang:
:expressionless:
:eye_speech_bubble:
:eye_speech_bubble:
:eye_speech_bubble:
:eye_speech_bubble:
:kissing_heart:
:yum:
:scream:
:vomiting_face:
:dizzy_face:
:face_with_crossed_out_eyes:
:knocked_out_face:
:hand_over_mouth:
:face_with_head_bandage:
:mask:
:monocle_face:
:open_mouth:
:raised_eyebrow:
:roll_eyes:
:triumph:
:cursing_face:
:joy:
:stuck_out_tongue:
:no_mouth:
:fast_forward:
:fast_forward_button:
:arrow_double_down:
:rewind:
:arrow_double_up:
:fax:
:fearful:
:field_hockey_stick_and_ball:
:film_strip:
:film_strip:
:first_quarter_moon_with_face:
:fish_cake:
:fishing_pole_and_fish:
:clock530:
:five_thirty:
:clock5:
:five_oclock:
:golf:
:fleur_de_lis:
:fleur_de_lis:
:muscle:
:flushed:
:pray:
:plate_with_cutlery:
:plate_with_cutlery:
:lower_left_fountain_pen:
:lower_left_fountain_pen:
:clock430:
:four_thirty:
:clock4:
:four_oclock:
:fox_face:
:frame_with_picture:
:frame_with_picture:
:fries:
:hatched_chick:
:front_facing_baby_chick:
:white_frowning_face:
:white_frowning_face:
:frowning:
:fuelpump:
:full_moon_with_face:
:gem:
:milk_glass:
:eyeglasses:
:earth_americas:
:globe_showing_americas:
:earth_asia:
:globe_showing_asia_australia:
:earth_africa:
:globe_showing_europe_africa:
:star2:
:japanese_goblin:
:harambe:
:mortar_board:
:grimacing:
:smiley_cat:
:smile_cat:
:grinning:
:smiley:
:smile:
:sweat_smile:
:satisfied:
:laughing:
:heartpulse:
:raised_hand_with_fingers_splayed:
:raised_hand_with_fingers_splayed:
:headphones:
:hear_no_evil:
:hear_no_evil_monkey:
:heavy_heart_exclamation:
:heavy_heart_exclamation_mark_ornament:
:heavy_heart_exclamation:
:heavy_heart_exclamation_mark_ornament:
:hearts:
:hearts:
:cupid:
:gift_heart:
:high_heel:
:high_heeled_shoe:
:bullettrain_side:
:high_speed_train:
:zap:
:o:
:bee:
:traffic_light:
:racehorse:
:horse:
:coffee:
:hotdog:
:hotsprings:
:hotsprings:
:hourglass:
:hourglass_flowing_sand:
:house_buildings:
:house_buildings:
:100:
:hushed:
:ice_cube:
:ice_hockey_stick_and_puck:
:point_up:
:point_up:
:information_source:
:information_source:
:abc:
:abcd:
:capital_abcd:
:1234:
:symbols:
:jack_o_lantern:
:black_joker:
:hash:
:hash:
:asterisk:
:asterisk:
:zero:
:zero:
:one:
:one:
:ten:
:keycap_ten:
:two:
:two:
:three:
:three:
:four:
:four:
:five:
:five:
:six:
:six:
:seven:
:seven:
:eight:
:eight:
:nine:
:nine:
:couplekiss:
:couplekiss_man_man:
:couplekiss_man_man:
:kiss:
:couplekiss_man_woman:
:couplekiss_man_woman:
:couplekiss_woman_woman:
:couplekiss_woman_woman:
:kissing:
:kissing_closed_eyes:
:kissing_smiling_eyes:
:hocho:
:knife:
:beetle:
:computer:
:last_quarter_moon_with_face:
:previous_track_button:
:black_left_pointing_double_triangle_with_vertical_bar:
:previous_track_button:
:black_left_pointing_double_triangle_with_vertical_bar:
:leaves:
:fist_left:
:left_facing_fist:
:left_right_arrow:
:left_right_arrow:
:arrow_left:
:arrow_left:
:arrow_right_hook:
:arrow_right_hook:
:bulb:
:emoji_modifier_fitzpatrick_type_1_2:
:paperclips:
:paperclips:
:lion_face:
:put_litter_in_its_place:
:lock:
:closed_lock_with_key:
:lock_with_ink_pen:
:steam_locomotive:
:sob:
:love_you_gesture:
:mag:
:mag_right:
:mahjong:
:bald_man:
:biking_man:
:biking_man:
:blond_haired_man:
:blond_haired_man:
:basketball_man:
:bouncing_ball_man:
:basketball_man:
:bouncing_ball_man:
:basketball_man:
:bouncing_ball_man:
:basketball_man:
:bouncing_ball_man:
:bowing_man:
:bowing_man:
:climbing_man:
:climbing_man:
:construction_worker_man:
:construction_worker_man:
:curly_haired_man:
:male_detective:
:male_detective:
:male_detective:
:male_detective:
:elf_man:
:elf_man:
:fairy_man:
:fairy_man:
:frowning_man:
:frowning_man:
:genie_man:
:genie_man:
:no_good_man:
:ng_man:
:man_gesturing_no:
:no_good_man:
:ng_man:
:man_gesturing_no:
:ok_man:
:man_gesturing_ok:
:ok_man:
:man_gesturing_ok:
:haircut_man:
:haircut_man:
:massage_man:
:massage_man:
:golfing_man:
:golfing_man:
:golfing_man:
:golfing_man:
:guardsman:
:guardsman:
:lotus_position_man:
:lotus_position_man:
:sauna_man:
:sauna_man:
:kneeling_man:
:kneeling_man:
:weight_lifting_man:
:weight_lifting_man:
:weight_lifting_man:
:weight_lifting_man:
:mage_man:
:mage_man:
:mountain_biking_man:
:mountain_biking_man:
:policeman:
:policeman:
:pouting_man:
:pouting_man:
:raising_hand_man:
:raising_hand_man:
:red_haired_man:
:rowing_man:
:rowing_man:
:running_man:
:running_man:
:standing_man:
:standing_man:
:superhero_man:
:superhero_man:
:supervillain_man:
:supervillain_man:
:surfing_man:
:surfing_man:
:swimming_man:
:swimming_man:
:sassy_man:
:tipping_hand_man:
:sassy_man:
:tipping_hand_man:
:vampire_man:
:vampire_man:
:walking_man:
:walking_man:
:man_with_turban:
:man_with_turban:
:white_haired_man:
:man_with_probing_cane:
:zombie_man:
:zombie_man:
:mans_shoe:
:shoe:
:japan:
:map_of_japan:
:emoji_modifier_fitzpatrick_type_5:
:emoji_modifier_fitzpatrick_type_3:
:emoji_modifier_fitzpatrick_type_4:
:mega:
:pencil:
:two_men_holding_hands:
:dancing_men:
:dancing_men:
:menorah_with_nine_branches:
:mens:
:mens_room:
:fu:
:reversed_hand_with_middle_finger_extended:
:medal_military:
:medal_military:
:heavy_minus_sign:
:moyai:
:iphone:
:calling:
:money_mouth_face:
:moneybag:
:rice_scene:
:racing_motorcycle:
:racing_motorcycle:
:mouse2:
:mouse:
:lips:
:heavy_multiplication_x:
:heavy_multiplication_x:
:notes:
:mute:
:nail_care:
:new_moon_with_face:
:black_right_pointing_double_triangle_with_vertical_bar:
:black_right_pointing_double_triangle_with_vertical_bar:
:clock930:
:nine_thirty:
:clock9:
:nine_oclock:
:do_not_litter:
:underage:
:non_potable_water:
:office:
:japanese_ogre:
:older_man:
:older_woman:
:older_adult:
:om_symbol:
:om_symbol:
:fist_oncoming:
:punch:
:facepunch:
:one_piece_swimsuit:
:clock130:
:one_thirty:
:clock1:
:one_oclock:
:book:
:mailbox_with_no_mail:
:mailbox_with_mail:
:cd:
:lower_left_paintbrush:
:lower_left_paintbrush:
:panda_face:
:tada:
:double_vertical_bar:
:double_vertical_bar:
:feet:
:lower_left_ballpoint_pen:
:lower_left_ballpoint_pen:
:pencil2:
:pencil2:
:pensive:
:dancers:
:wrestling:
:persevere:
:adult:
:bearded_person:
:bicyclist:
:blond_haired_person:
:person_with_blond_hair:
:bouncing_ball_person:
:person_with_ball:
:bouncing_ball_person:
:person_with_ball:
:bow:
:cartwheeling:
:climbing:
:facepalm:
:frowning_person:
:no_good:
:person_gesturing_no:
:ok_person:
:person_gesturing_ok:
:haircut:
:massage:
:golfing:
:golfer:
:golfing:
:golfer:
:sleeping_bed:
:sleeping_accommodation:
:lotus_position:
:sauna_person:
:business_suit_levitating:
:man_in_business_suit_levitating:
:business_suit_levitating:
:man_in_business_suit_levitating:
:juggling_person:
:kneeling_person:
:weight_lifting:
:weight_lifter:
:weight_lifting:
:weight_lifter:
:mountain_bicyclist:
:handball_person:
:water_polo:
:pouting_face:
:person_with_pouting_face:
:raising_hand:
:rowboat:
:runner:
:running:
:shrug:
:standing_person:
:surfer:
:swimmer:
:bath:
:tipping_hand_person:
:information_desk_person:
:walking:
:person_with_turban:
:man_with_gua_pi_mao:
:person_with_probing_cane:
:pig2:
:pig:
:poop:
:hankey:
:shit:
:bamboo:
:table_tennis_paddle_and_ball:
:pinata:
:arrow_forward:
:arrow_forward:
:black_right_pointing_triangle_with_double_vertical_bar:
:black_right_pointing_triangle_with_double_vertical_bar:
:heavy_plus_sign:
:rotating_light:
:cop:
:8ball:
:european_post_office:
:stew:
:pound:
:no_entry_sign:
:jigsaw:
:rabbit2:
:rabbit:
:radioactive_sign:
:radioactive_sign:
:fist:
:fist_raised:
:hand:
:raised_hands:
:black_circle_for_record:
:black_circle_for_record:
:recycle:
:recycle:
:apple:
:heavy_exclamation_mark:
:exclamation:
:heart:
:heart:
:izakaya_lantern:
:lantern:
:question:
:small_red_triangle_down:
:small_red_triangle:
:relieved:
:repeat:
:repeat_one:
:helmet_with_white_cross:
:rescue_worker_helmet:
:rescue_workers_helmet:
:helmet_with_white_cross:
:rescue_worker_helmet:
:rescue_workers_helmet:
:arrow_backward:
:arrow_backward:
:fist_right:
:right_facing_fist:
:arrow_right:
:arrow_right:
:arrow_heading_down:
:arrow_heading_down:
:leftwards_arrow_with_hook:
:leftwards_arrow_with_hook:
:arrow_heading_up:
:arrow_heading_up:
:sweet_potato:
:robot_face:
:rolled_up_newspaper:
:newspaper_roll:
:rolled_up_newspaper:
:newspaper_roll:
:rofl:
:running_shirt_with_sash:
:athletic_shoe:
:disappointed_relieved:
:boat:
:artificial_satellite:
:artificial_satellite:
:satellite:
:see_no_evil:
:see_no_evil_monkey:
:clock730:
:seven_thirty:
:clock7:
:seven_oclock:
:ear_of_rice:
:stars:
:shopping:
:shopping:
:cake:
:twisted_rightwards_arrows:
:metal:
:clock630:
:six_thirty:
:clock6:
:six_oclock:
:ski:
:sleeping:
:sleepy:
:heart_eyes_cat:
:smiling_cat_with_heart_eyes:
:relaxed:
:relaxed:
:innocent:
:heart_eyes:
:smiling_face_with_heart_eyes:
:smiling_face_with_three_hearts:
:smiling_imp:
:hugging_face:
:hugs:
:blush:
:sunglasses:
:smirk:
:mountain_snow:
:snow_capped_mountain:
:mountain_snow:
:snow_capped_mountain:
:snowman_with_snow:
:snowman_with_snow:
:snowman:
:soccer:
:icecream:
:spades:
:spades:
:speak_no_evil:
:speak_no_evil_monkey:
:loud_sound:
:speaker:
:sound:
:speaking_head_in_silhouette:
:speaking_head_in_silhouette:
:spiral_calendar_pad:
:spiral_calendar_pad:
:spiral_note_pad:
:spiral_note_pad:
:shell:
:blue_car:
:medal_sports:
:whale:
:stuck_out_tongue_closed_eyes:
:star_struck:
:star_of_david:
:star_of_david:
:ramen:
:black_square_for_stop:
:black_square_for_stop:
:sunny:
:sunny:
:partly_sunny:
:white_sun_behind_cloud:
:white_sun_behind_cloud:
:white_sun_behind_cloud_with_rain:
:white_sun_behind_cloud_with_rain:
:white_sun_with_small_cloud:
:white_sun_with_small_cloud:
:dark_sunglasses:
:dark_sunglasses:
:city_sunrise:
:sweat_drops:
:tshirt:
:shirt:
:t_shirt:
:orange:
:mandarin:
:tea:
:calendar:
:tear_off_calendar:
:phone:
:phone:
:tv:
:clock1030:
:ten_thirty:
:clock10:
:ten_oclock:
:thinking:
:clock330:
:three_thirty:
:clock3:
:three_oclock:
:thumbsdown:
:_1:
:-1:
:thumbsup:
:+1:
:tiger2:
:tiger:
:tophat:
:cloud_with_tornado:
:cloud_with_tornado:
:tm:
:tm:
:train2:
:train:
:triangular_flag_on_post:
:trident:
:clock1230:
:twelve_thirty:
:clock12:
:twelve_oclock:
:camel:
:two_hump_camel:
:clock230:
:two_thirty:
:clock2:
:two_oclock:
:open_umbrella:
:open_umbrella:
:parasol_on_ground:
:parasol_on_ground:
:umbrella:
:unamused:
:unicorn_face:
:unlock:
:arrow_up_down:
:up_down_arrow:
:arrow_up_down:
:up_down_arrow:
:arrow_upper_left:
:up_left_arrow:
:arrow_upper_left:
:up_left_arrow:
:arrow_upper_right:
:up_right_arrow:
:arrow_upper_right:
:up_right_arrow:
:arrow_up:
:arrow_up:
:upside_down_face:
:arrow_up_small:
:v:
:v:
:vhs:
:raised_hand_with_part_between_middle_and_ring_fingers:
:wc:
:gun:
:ocean:
:wave:
:moon:
:scream_cat:
:weary:
:whale2:
:wheelchair:
:probing_cane:
:grey_exclamation:
:waving_white_flag:
:waving_white_flag:
:white_medium_small_square:
:grey_question:
:wind_blowing_face:
:wind_blowing_face:
:wink:
:stuck_out_tongue_winking_eye:
:couple:
:bald_woman:
:biking_woman:
:biking_woman:
:blonde_woman:
:blond_haired_woman:
:blonde_woman:
:blond_haired_woman:
:basketball_woman:
:bouncing_ball_woman:
:basketball_woman:
:bouncing_ball_woman:
:basketball_woman:
:bouncing_ball_woman:
:basketball_woman:
:bouncing_ball_woman:
:bowing_woman:
:bowing_woman:
:climbing_woman:
:climbing_woman:
:construction_worker_woman:
:construction_worker_woman:
:curly_haired_woman:
:dancer:
:female_detective:
:female_detective:
:female_detective:
:female_detective:
:elf_woman:
:elf_woman:
:fairy_woman:
:fairy_woman:
:frowning_woman:
:frowning_woman:
:genie_woman:
:genie_woman:
:ng_woman:
:no_good_woman:
:woman_gesturing_no:
:ng_woman:
:no_good_woman:
:woman_gesturing_no:
:ok_woman:
:woman_gesturing_ok:
:ok_woman:
:woman_gesturing_ok:
:haircut_woman:
:haircut_woman:
:massage_woman:
:massage_woman:
:golfing_woman:
:golfing_woman:
:golfing_woman:
:golfing_woman:
:guardswoman:
:guardswoman:
:lotus_position_woman:
:lotus_position_woman:
:sauna_woman:
:sauna_woman:
:kneeling_woman:
:kneeling_woman:
:weight_lifting_woman:
:weight_lifting_woman:
:weight_lifting_woman:
:weight_lifting_woman:
:mage_woman:
:mage_woman:
:mountain_biking_woman:
:mountain_biking_woman:
:policewoman:
:policewoman:
:pouting_woman:
:pouting_woman:
:raising_hand_woman:
:raising_hand_woman:
:red_haired_woman:
:rowing_woman:
:rowing_woman:
:running_woman:
:running_woman:
:standing_woman:
:standing_woman:
:superhero_woman:
:superhero_woman:
:supervillain_woman:
:supervillain_woman:
:surfing_woman:
:surfing_woman:
:swimming_woman:
:swimming_woman:
:sassy_woman:
:tipping_hand_woman:
:sassy_woman:
:tipping_hand_woman:
:vampire_woman:
:vampire_woman:
:walking_woman:
:walking_woman:
:woman_with_turban:
:woman_with_turban:
:white_haired_woman:
:bride_with_veil:
:bride_with_veil:
:woman_with_probing_cane:
:zombie_woman:
:zombie_woman:
:boot:
:womans_boot:
:womans_clothes:
:womans_hat:
:sandal:
:womans_sandal:
:two_women_holding_hands:
:dancing_women:
:dancing_women:
:womens:
:womens_room:
:worried:
:gift:
:x_ray:
:yen:
:yo_yo:
:zipper_mouth_face:
:flag_for_Åland_Islands:
:aland_islands:"""
