#
# ███╗   ███╗██████╗ ██████╗ ██╗  ██╗
# ████╗ ████║╚═══╗██╗██╔══██╗██║ ██╔╝
# ██╔████╔██║███████║██████╔╝█████╔╝
# ██║╚██╔╝██║██╔══██║██╔══██╗██╔═██╗
# ██║ ╚═╝ ██║ █████╔╝██║  ██║██║  ██╗
# ╚═╝     ╚═╝ ╚════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
# Copyright (C) 2025  Daniel Hetrick
# https://github.com/nutjob-laboratories/merk
# https://github.com/nutjob-laboratories
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

EXAMPLE_PLUGIN="""#
# ███╗   ███╗██████╗ ██████╗ ██╗  ██╗ 
# ████╗ ████║╚═══╗██╗██╔══██╗██║ ██╔╝ 
# ██╔████╔██║███████║██████╔╝█████╔╝  
# ██║╚██╔╝██║██╔══██║██╔══██╗██╔═██╗ 
# ██║ ╚═╝ ██║ █████╔╝██║  ██║██║  ██╗
# ╚═╝     ╚═╝ ╚════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
# 
# |------------------------------------------|
# | This is a plugin for the MERK IRC Client |
# |------------------------------------------|
#
# Plugin code generated by %__FULL_VERSION__%
#
# Information on how to use inherited plugin methods
# and how to write MERK plugins can be found in the
# MERK User Manual.
#
# Inherited methods: alias, all_channels, all_masters,
#                    all_privates, all_windows, channel,
#                    channels, clients, find, home, ignore,
#                    ignores, is_away, list, master, max,
#                    maximized, min, minimized, private,
#                    privates, restore, unignore, windows

from merk import Plugin

class ExamplePlugin(Plugin):

    #   NAME = The name of the plugin
    #   AUTHOR = The person or group that wrote the plugin
    #   VERSION = The plugin's version number
    #   SOURCE = The URL for the plugins source code or website

    NAME = "Example Plugin"
    AUTHOR = "MERK"
    VERSION = "1.0"
    SOURCE = "https://github.com/nutjob-laboratories/merk"

    # |---------------------|
    # | BEGIN PLUGIN EVENTS |
    # |---------------------|

    # All arguments passed to events are strings, unless
    # otherwise specified. Event methods should not return
    # anything; if they do, the return value will be ignored.

    # |======|
    # | init |
    # |======|
    #
    # This event is triggered when the plugin is loaded.
    # It will only be triggered once.
    #
    # Arguments:
    #   None
    #
    def init(self):
        pass

    # |========|
    # | action |
    # |========|
    #
    # This event is triggered whenever MERK receives a
    # CTCP action message.
    #
    # Arguments:
    #   window = MERK Window
    #   channel = The channel where the event occurred
    #   user = The user that sent the message
    #   message = The text of the message
    #
    def action(self,**args):
        window = args["window"]
        channel = args["channel"]
        user = args["user"]
        message = args["message"]

    # |==========|
    # | activate |
    # |==========|
    #
    # This event is triggered whenever a server, channel,
    # or private chat window gains focus.
    #
    # Arguments:
    #   client = MERK Window
    #
    def activate(self,**args):
        window = args["window"]

    # |======|
    # | away |
    # |======|
    #
    # This event is triggered whenever a user changes their
    # status to "away" in the presence of the MERK client.
    #
    # Arguments:
    #   client = The Twisted IRC object that triggered the event
    #   user = The user that went away
    #   message - The user's away message
    #
    def away(self,**args):
        client = args["client"]
        user = args["user"]
        message = args["message"]

    # |======|
    # | back |
    # |======|
    #
    # This event is triggered whenever a user changes their
    # status to "back" in the presence of the MERK client.
    #
    # Arguments:
    #   client = The Twisted IRC object that triggered the event
    #   user = The user that came back
    #
    def back(self,**args):
        client = args["client"]
        user = args["user"]

    # |=======|
    # | close |
    # |=======|
    #
    # This event is triggered whenever a chat subwindow is closed.
    #
    # Arguments:
    #   name = The name of the subwindow
    #
    def close(self,**args):
        name = args["name"]

    # |===========|
    # | connected |
    # |===========|
    #
    # This event is triggered whenever a MERK has completed
    # connection to an IRC server.
    #
    # Arguments:
    #   window = MERK Window object
    #
    def connected(self,**args):
        window = args["window"]

    # |============|
    # | connecting |
    # |============|
    #
    # This event is triggered whenever a MERK has begins
    # connecting to an IRC server. If the Twisted IRC object
    # is used to issue commands, they probably won't work.
    #
    # Arguments:
    #   client = The Twisted IRC object that triggered the event
    #
    def connecting(self,**args):
        client = args["client"]

    # |=======|
    # | ctick |
    # |=======|
    #
    # This event is triggered once a second, every second
    # that MERK is running.
    #
    # Arguments:
    #   uptime = The number of seconds that MERK has been
    #            running.
    #
    def ctick(self,**args):
        uptime = args["uptime"]

    # |============|
    # | disconnect |
    # |============|
    #
    # This event is triggered whenever MERK issues the "quit"
    # command and disconnects from an IRC server.
    #
    # Arguments:
    #   client = The Twisted IRC object that triggered the event
    #   message = The quit message used
    #
    def disconnect(self,**args):
        client = args["client"]
        message = args["message"]

    # |=======|
    # | error |
    # |=======|
    #
    # This event is triggered whenever MERK receives an error
    # message from an IRC server.
    #
    # Arguments:
    #   client = The Twisted IRC object that triggered the event
    #   message = The error message
    #
    def error(self,**args):
        client = args["client"]
        message = args["message"]

    # |========|
    # | invite |
    # |========|
    #
    # This event is triggered whenever a channel invite is
    # received.
    #
    # Arguments:
    #   client = The Twisted IRC object that triggered the event
    #   user = The user that sent the invite
    #   channel = The channel the user invited the client to join
    #
    def invite(self,**args):
        client = args["client"]
        user = args["user"]
        channel = args["channel"]

    # |======|
    # | join |
    # |======|
    #
    # This event is triggered user joins a channel in the 
    # presence of MERK.
    #
    # Arguments:
    #   window = MERK Window
    #   channel = The channel the user joined
    #   user = The user joined
    #
    def join(self,**args):
        window = args["window"]
        channel = args["channel"]
        user = args["user"]

    # |========|
    # | joined |
    # |========|
    #
    # This event is triggered whenever MERK joins a channel
    #
    # Arguments:
    #   channel = The channel MERK joined
    #   window = MERK Window
    #
    def joined(self,**args):
        channel = args["channel"]
        window = args["window"]

    # |======|
    # | kick |
    # |======|
    #
    # This event is triggered whenever a user is kicked from
    # a channel in MERK's presence
    #
    # Arguments:
    #   window = MERK Window
    #   channel = The channel the user was kicked from
    #   user = The user that issued the kick
    #   target = The user that was kicked
    #   message = The kick message, if one was supplied
    #
    def kick(self,**args):
        window = args["window"]
        channel = args["channel"]
        user = args["user"]
        target = args["target"]
        message = args["message"]

    # |========|
    # | kicked |
    # |========|
    #
    # This event is triggered the user is kicked from a
    # channel.
    #
    # Arguments:
    #   client = The Twisted IRC object that triggered the event
    #   channel = The channel the user was kicked from
    #   user = The user that issued the kick
    #   message = The kick message, if one was supplied
    #
    def kicked(self,**args):
        client = args["client"]
        channel = args["channel"]
        user = args["user"]
        message = args["message"]

    # |======|
    # | left |
    # |======|
    #
    # This event is triggered whenever MERK leaves a channel.
    #
    # Arguments:
    #   window = The Twisted IRC object that triggered the event
    #   channel = The channel MERK left
    #
    def left(self,**args):
        client = args["client"]
        channel = args["channel"]

    # |=========|
    # | line_in |
    # |=========|
    #
    # This event is triggered whenever a connected Twisted IRC
    # client object receives data from an IRC server.
    #
    # Arguments:
    #   client = The Twisted IRC object that triggered the event
    #   line = Bytes, UTF-8 encoded string. The data received
    #          from the server
    #
    def line_in(self,**args):
        client = args["client"]
        line = args["line"]

    # |==========|
    # | line_out |
    # |==========|
    #
    # This event is triggered whenever a connected Twisted IRC
    # client object sends data to an IRC server.
    #
    # Arguments:
    #   client = The Twisted IRC object that triggered the event
    #   line = The data sent to the IRC server.
    #
    def line_out(self,**args):
        client = args["client"]
        line = args["line"]

    # |======|
    # | lost |
    # |======|
    #
    # This event is triggered whenever a connection to an IRC
    # server is "lost"; that is, disconnected via a method that
    # is not called for, such as a lost of Internet connection
    # k-line, etc.
    #
    # Arguments:
    #   client = The Twisted IRC object that triggered the event
    #
    def lost(self,**args):
        client = args["client"]

    # |====|
    # | me |
    # |====|
    #
    # This event is triggered whenever MERK sends a channel or
    # private chat message. If the target does not have a subwindow
    # open for it, the "window" argument will be set to None.
    #
    # Arguments:
    #   window = MERK Window
    #   client = The Twisted IRC object that sent the message
    #   target = The channel or user the message was sent to
    #   message = The message
    #
    def me(self,**args):
        window = args["window"]
        client = args["client"]
        target = args["target"]
        message = args["message"]

    # |=========|
    # | message |
    # |=========|
    #
    # This event is triggered whenever MERK received a channel
    # or private chat message. If the message is a private chat
    # message, the channel will be MERK's nickname.
    #
    # Arguments:
    #   window = MERK Window
    #   channel = The channel the message was sent to
    #   user = The user that sent the message
    #   message = The message
    #
    def message(self,**args):
        window = args["window"]
        channel = args["channel"]
        user = args["user"]
        message = args["message"]

    # |======|
    # | mode |
    # |======|
    #
    # This event is triggered whenever a mode is set in
    # MERK's presence. This can be a user mode or a channel
    # mode.
    #
    # Arguments:
    #   client = The Twisted IRC object that triggered the event
    #   user = The user that set the mode
    #   target = The user or channel the mode was set on
    #   mode = The mode(s) applied
    #   arguments = Tuple. Any arguments passed to the mode.
    #
    def mode(self,**args):
        client = args["client"]
        user = args["user"]
        target = args["target"]
        mode = args["mode"]
        arguments = args["arguments"]

    # |======|
    # | motd |
    # |======|
    #
    # This event is triggered whenever the message of the
    # day is received from an IRC server.
    #
    # Arguments:
    #   client = The Twisted IRC object that triggered the event
    #   text = The text of the MOTD
    #
    def motd(self,**args):
        client = args["client"]
        text = args["text"]

    # |======|
    # | nick |
    # |======|
    #
    # This event is triggered whenever MERK changes nicknames.
    # This will also be triggered during registration with an
    # IRC server, when the user's nickname is first set.
    #
    # Arguments:
    #   client = The Twisted IRC object that triggered the event
    #   nickname = The new nickname
    #
    def nick(self,**args):
        client = args["client"]
        newnick = args["nickname"]

    # |========|
    # | notice |
    # |========|
    #
    # This event is triggered whenever MERK received a channel
    # or private notice. If the message is a private chat
    # notice, the channel will be MERK's nickname.
    #
    # Arguments:
    #   window = MERK Window
    #   channel = The channel the notice was sent to
    #   user = The user that sent the notice
    #   message = The message
    #
    def notice(self,**args):
        window = args["window"]
        channel = args["channel"]
        user = args["user"]
        message = args["message"]

    # |======|
    # | part |
    # |======|
    #
    # This event is triggered whenever a user leaves a channel
    # in MERK's presence.
    #
    # Arguments:
    #   window = MERK Window
    #   channel = The channel the user left
    #   user = The user that left
    #
    def part(self,**args):
        window = args["window"]
        channel = args["channel"]
        user = args["user"]

    # |======|
    # | ping |
    # |======|
    #
    # This event is triggered whenever the server sends a
    # ping to the client.
    #
    # Arguments:
    #   client = Twisted IRC object that triggered the event
    #
    def ping(self,**args):
        client = args["client"]

    # |======|
    # | quit |
    # |======|
    #
    # This event is triggered whenever a user disconnects from
    # from IRC in MERK's presence.
    #
    # Arguments:
    #   client = The Twisted IRC object that triggered the event
    #   user = The user that disconnected
    #   message = The quit message, if the user used one
    #
    def quit(self,**args):
        client = args["client"]
        user = args["user"]
        message = args["message"]

    # |========|
    # | rename |
    # |========|
    #
    # This event is triggered whenever a user changes their
    # nickname in MERK's presence.
    #
    # Arguments:
    #   client = The Twisted IRC object that triggered the event
    #   old = The user's old nickname
    #   new = The user's new nickname
    #
    def rename(self,**args):
        client = args["client"]
        old_name = args["old"]
        new_name = args["new"]

    # |========|
    # | server |
    # |========|
    #
    # This event is triggered if a server message is received.
    #
    # Arguments:
    #   client = The Twisted IRC object that triggered the event
    #   message = The message
    #
    def server(self,**args):
        client = args["client"]
        message = args["message"]

    # |===========|
    # | subwindow |
    # |===========|
    #
    # This event is triggered whenever a new chat subwindow is
    # created.
    #
    # Arguments:
    #   window = MERK Window
    #
    def subwindow(self,**args):
        window = args["window"]

    # |======|
    # | tick |
    # |======|
    #
    # This event is triggered once a second, every second
    # that a Twisted IRC client object is connected to an
    # IRC server.
    #
    # Arguments:
    #   client = The Twisted IRC object that triggered the event
    #   uptime = The number of seconds that the Twisted IRC
    #            client object has been connected to the IRC
    #            server
    #
    def tick(self,**args):
        client = args["client"]
        uptime = args["uptime"]

    # |=======|
    # | topic |
    # |=======|
    #
    # This event is triggered whenever a channel's topic
    # changes in MERK's presence. This will also be triggered
    # when MERK joins a channel.
    #
    # Arguments:
    #   window = MERK Window
    #   user = The user that set the topic. This may be the
    #          server's name
    #   channel = The channel the topic was set on
    #   topic = The topic that was set
    #
    def topic(self,**args):
        window = args["window"]
        user = args["user"]
        channel = args["channel"]
        topic = args["topic"]

    # |========|
    # | unmode |
    # |========|
    #
    # This event is triggered whenever a mode is removed in
    # MERK's presence. This can be a user mode or a channel
    # mode.
    #
    # Arguments:
    #   client = The Twisted IRC object that triggered the event
    #   user = The user that removed the mode
    #   target = The user or channel the mode was removed from
    #   mode = The mode(s) removed
    #   arguments = Tuple. Any arguments passed to the mode removal
    #
    def unmode(self,**args):
        client = args["client"]
        user = args["user"]
        target = args["target"]
        mode = args["mode"]
        arguments = args["arguments"]

    # |-------------------|
    # | END PLUGIN EVENTS |
    # |-------------------|
"""
