#
# ███╗   ███╗██████╗ ██████╗ ██╗  ██╗
# ████╗ ████║╚═══╗██╗██╔══██╗██║ ██╔╝
# ██╔████╔██║███████║██████╔╝█████╔╝
# ██║╚██╔╝██║██╔══██║██╔══██╗██╔═██╗
# ██║ ╚═╝ ██║ █████╔╝██║  ██║██║  ██╗
# ╚═╝     ╚═╝ ╚════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
# Copyright (C) 2026  Daniel Hetrick
# https://github.com/nutjob-laboratories/merk
# https://github.com/nutjob-laboratories
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

NETWORK_LINKS="""Abjects:https://abjects.net/
AfterNET:https://www.afternet.org/
AllNightCafe:https://allnightcafe.org/
BrasIRC:https://www.brasirc.org/
Chatzona:https://www.chatzona.net/
DigitalIRC:https://www.digitalirc.org/
EuropNet:https://www.europnet.org/
Freenode:https://freenode.net/
FurNet:https://furrent.org/
IRCCloud:https://irccloud.com/
IRCHighWay:https://www.irchighway.net/
LewdChat:https://lewdchat.com/
LinkNet:https://www.link-net.org/
MozillaIRC:https://wiki.mozilla.org/IRC
Libera.Chat:https://libera.chat/
OFTC:https://www.oftc.net/
Undernet:https://www.undernet.org/
IRCnet:http://www.ircnet.org/
EFnet:http://www.efnet.org/
DALnet:http://www.dal.net/
QuakeNet:http://www.quakenet.org/
Rizon:http://www.rizon.net/
Snoonet:https://snoonet.org/
GameSurge:http://www.gamesurge.net/
SwiftIRC:http://www.swiftirc.net/
EsperNet:https://www.esper.net/
IRC-Hispano:https://www.irc-hispano.es/
DarkMyst:http://www.darkmyst.org/
GeekShed:https://www.geeksh.ed/
GimpNet:https://www.gimpnet.org/
Ogame:https://www.ogame.org/
SlashNET:https://slashnet.org/
MansionNET:https://inthemansion.com/
2600net:https://2600.net/
Abandoned-IRC:https://abandoned-irc.net/
AfterNET:http://www.afternet.org/
AllNightCafe:https://allnightcafe.com/
AlphaChat:https://www.alphachat.net/
"""

NETWORK_LIST = """irc.2600.net:6667:2600net:normal
irc.2600.net:6697:2600net:ssl
irc-eu.scuttled.net:6667:2600net:normal
irc.abandoned-irc.net:6667:Abandoned-IRC:normal
irc.afternet.org:6667:AfterNET:normal
irc.data.lt:6667:Aitvaras:normal
irc.ktu.lt:6667:Aitvaras:normal
irc.omnitel.net:6667:Aitvaras:normal
irc.allnetwork.org:6667:AllNetwork:normal
irc.allnightcafe.com:6667:AllNightCafe:normal
irc.allnightcafe.com:6697:AllNightCafe:ssl
irc.alphachat.net:6697:AlphaChat:ssl
irc.animefriends.moe:7000:AnimeFriends:ssl
irc.anonops.com:6697:AnonOps:ssl
irc.anonops.com:6667:AnonOps:normal
irc.atrum.org:6667:Atrum:normal
irc.austnet.org:6667:AustNet:normal
irc.ayochat.or.id:6667:AyoChat:normal
irc.ayochat.or.id:6697:AyoChat:ssl
irc.azzurra.chat:6697:Azzurra:ssl
irc.azzurra.chat:6667:Azzurra:normal
irc.bgirc.com:6667:BGirc.com:normal
irc.bolchat.com:6667:BOLChat:normal
irc.brasirc.com.br:6667:BrasIRC:normal
celestia.canternet.org:6667:Canternet:normal
luna.canternet.org:6667:Canternet:normal
derpy.canternet.org:6667:Canternet:normal
irc.chaat.fr:6667:Chaat:normal
irc.chaat.fr:6697:Chaat:ssl
irc.chat4all.org:6668:Chat4All.org:normal
irc.chateo.org:6697:Chateo:ssl
irc.chateo.org:6667:Chateo:normal
irc.chatlife.net:6697:ChatLife:ssl
irc.chatlife.net:6667:ChatLife:normal
irc.chatlounge.net:6667:ChatLounge:normal
irc.chatsansar.com:6667:ChatSansar:normal
irc.chatsansar.com:6697:ChatSansar:ssl
irc.chattersnet.nl:6667:Chattersnet:normal
irc.chattersnet.nl:6697:Chattersnet:ssl
irc.chatzona.org:6667:Chatzona:normal
irc.coolsmile.net:6667:Coolsmile.net:normal
irc.coolsmile.net:6697:Coolsmile.net:ssl
irc.cuff-link.me:6697:Cuff-Link:ssl
irc.cyberirc.org:6697:CyberIRC:ssl
irc.cyberirc.org:6667:CyberIRC:normal
irc.dal.net:6667:DALnet:normal
ix.dal.net:6667:DALnet:normal
irc.darkfasel.net:6697:darkfasel.net:ssl
irc2.darkmyst.org:6667:DarkMyst:normal
irc.darkscience.net:6667:darkscience:normal
irc.darchoods.net:6697:darkscience:ssl
irc.darkscience.net:6697:darkscience:ssl
irc.darkworld.network:6697:DarkWorld:ssl
irc.dejatoons.net:6667:DejaToons:normal
irc.desirenet.org:6667:DesireNet:normal
irc.digitalirc.org:6667:DigitalIRC:normal
irc.digitalirc.org:6697:DigitalIRC:ssl
studio64.yi.org:6667:DorksNet:normal
irc.dreams-fr.net:6667:dreams-fr:normal
irc.efes.net:6697:EfesNet:ssl
irc.adres.net:6697:EfesNet:ssl
irc.hasret.net:6697:EfesNet:ssl
irc.efnet.org:6667:EFnet:normal
irc.efnet.org:6697:EFnet:ssl
irc.efnet.nl:6667:EFnet:normal
irc.epiknet.org:6667:EpiKnet:normal
damocles.esper.net:6667:EsperNet:normal
chocobo.esper.net:6667:EsperNet:normal
irc.esper.net:6667:EsperNet:normal
irc.euirc.net:6667:euIRC:normal
irc.bas.ch.euirc.net:6667:euIRC:normal
irc.ham.de.euirc.net:6667:euIRC:normal
irc.hes.de.euirc.net:6667:euIRC:normal
irc.inn.at.euirc.net:6667:euIRC:normal
irc.rbx.fr.euirc.net:6667:euIRC:normal
irc.nbg.de.euirc.net:6667:euIRC:normal
irc.ams.nl.euirc.net:6667:euIRC:normal
irc.europnet.org:6667:EuropNet:normal
irc.evilnet.org:6667:EvilNET:normal
irc.evilnet.org:6697:EvilNET:ssl
irc.evochat.co.id:6667:EvoChat:normal
irc.evochat.co.id:6697:EvoChat:ssl
irc.evolu.net:6667:Evolu.NET:normal
sivit.fr.eu.evolu.net:6667:Evolu.NET:normal
irc.flexchat.org:6697:FlexChat:ssl
irc.flexchat.org:6667:FlexChat:normal
irc.forumcerdas.net:6697:ForumCerdas:ssl
irc.forumcerdas.net:6667:ForumCerdas:normal
chat.freenode.net:6697:freenode:ssl
chat.freenode.net:6667:freenode:normal
irc.freeunibg.eu:6697:FreeUniBG:ssl
irc.freeunibg.eu:6667:FreeUniBG:normal
irc.unibg.net:6697:FreeUniBG:ssl
irc.unibg.net:6667:FreeUniBG:normal
irc.gamesurge.net:6667:GameSurge:normal
irc.geeknode.org:6667:GeekNode:normal
irc.geekshed.net:6667:GeekShed:normal
irc.german-elite.net:6667:German-Elite:normal
irc.gigairc.net:6667:GigaIRC:normal
irc.gimp.org:6667:GIMPnet:normal
irc.global-irc.eu:6667:Global-Irc.Eu:normal
irc.global-irc.eu:6697:Global-Irc.Eu:ssl
irc.globalirc.it:6667:GlobalIRC.it:normal
irc.hackint.org:6697:hackint:ssl
irc.hackint.eu:6697:hackint:ssl
irc.hub4ever.org:6697:Hub4Ever.Org:ssl
irc.hub4ever.org:6667:Hub4Ever.Org:normal
irc.hybridirc.com:6667:HybridIRC:normal
irc.hybridirc.com:6697:HybridIRC:ssl
irc.icq-chat.com:6697:ICQ-Chat:ssl
irc.icq-chat.com:6667:ICQ-Chat:normal
irc.irc-hispano.org:6667:IRC-Hispano:normal
irc.chathispano.com:6667:IRC-Hispano:normal
irc.irc-nerds.net:6667:IRC-Nerds:normal
irc.irc-nerds.net:6697:IRC-Nerds:ssl
us.irc4fun.net:6667:IRC4Fun:normal
irc.irc4fun.net:6667:IRC4Fun:normal
irc.irccloud.com:6697:IRCCloud:ssl
irc.irccloud.com:6667:IRCCloud:normal
irc.irchighway.net:6667:IRCHighWay:normal
irc.us.ircnet.net:6697:IRCnet:ssl
irc.us.ircnet.net:6667:IRCnet:normal
irc.fu-berlin.de:6697:IRCnet:ssl
irc.ircnow.org:6697:IRCNow:ssl
irc.ircnow.org:6667:IRCNow:normal
irc.ircsource.net:6667:IRCsource:normal
irc.ircsource.net:6697:IRCsource:ssl
irc.jmeeting.com:8067:Jmeeting:normal
irc.kalbim.net:6667:Kalbim.Net:normal
irc.kampungchat.org:6667:KampungChat:normal
irc.lewdchat.com:6667:LewdChat:normal
irc.lewdchat.com:6697:LewdChat:ssl
irc.libera.chat:6697:Libera.Chat:ssl
irc.libera.chat:6667:Libera.Chat:normal
irc.librairc.net:6669:LibraIRC:normal
irc.librairc.net:6697:LibraIRC:ssl
irc.link-net.org:7000:LinkNet:ssl
irc.luatic.net:6667:Luatic:normal
irc.luatic.net:6697:Luatic:ssl
irc.lunarirc.net:6697:LunarIRC:ssl
irc.lunarirc.net:6667:LunarIRC:normal
irc.perl.org:6667:MagNET:normal
irc.inthemansion.com:6697:MansionNET:ssl
irc.mindforge.org:6667:MindForge:normal
irc.mixxnet.net:6667:MIXXnet:normal
irc.net-tchat.fr:6697:Net-Tchat:ssl
irc.nether.rip:6697:Nether.RIP:ssl
irc.netirc.eu:6667:NetIRC:normal
irc.newnet.net:6667:NewNet:normal
irc.newnet.net:6697:NewNet:ssl
irc.nightstar.net:6669:NightStar.Net:normal
irc.oftc.net:6667:OFTC:normal
irc.oftc.net:6697:OFTC:ssl
irc.optilan.eu:6667:OptiLan:normal
irc.orixon.org:9999:Orixon:ssl
irc.p2p-irc.net:6667:P2P-NET:normal
irc.p2p-network.net:6667:P2P-NET:normal
irc.pirc.pl:6667:PIRC.pl:normal
irc.ptirc.org:6697:PTirc:ssl
irc.ptnet.org:6667:PTnet:normal
irc.quakenet.org:6667:QuakeNet:normal
irc.retronode.org:6697:RetroNode:ssl
irc.rezosup.org:6667:RezoSup:normal
irc.as.rizon.net:6667:Rizon:normal
irc.rizon.net:6667:Rizon:normal
irc.eu.rizon.net:6667:Rizon:normal
irc.us.rizon.net:7000:Rizon:normal
irc.runxiyu.org:6697:runxiyu:ssl
shelltalk.net:6697:Shelltalk:ssl
shelltalk.net:6667:Shelltalk:normal
irc.simosnap.com:6667:SimosNap:normal
irc.simosnap.com:6697:SimosNap:ssl
irc.skychatz.org:6697:SkyChatz:ssl
irc.skychatz.org:6668:SkyChatz:normal
irc.slashnet.org:6667:SlashNET:normal
irc.smurfnet.ch:6667:Smurfnet:normal
irc.smurfnet.ch:6697:Smurfnet:ssl
irc.snoonet.org:6667:Snoonet:normal
irc.sohbetburada.com:6667:SohbetBurada:normal
irc.sohbetburada.com:6697:SohbetBurada:ssl
irc.sorcery.net:9000:SorceryNet:normal
irc.soyle.net:6697:soyle.net:ssl
irc.soyle.net:6667:soyle.net:normal
blub.de.spotchat.org:6667:SpotChat:normal
irc.spotchat.org:6667:SpotChat:normal
irc.srcf.net:6667:SRCF:normal
irc.station51.net:6667:Station51.net:normal
irc.swiftirc.net:6667:SwiftIRC:normal
irc.synirc.net:6667:synIRC:normal
irc.technet.chat:6667:TechNet:normal
irc.technet.chat:6697:TechNet:ssl
irc.teranova.net:6697:Teranova:ssl
irc.tilde.chat:6697:tilde.chat:ssl
irc.transadvice.org:6667:TransAdvice:normal
irc.transadvice.org:6697:TransAdvice:ssl
irc.trendsohbet.com:6667:TrendSohbet.Com:normal
irc.twistednet.org:6667:TwistedNet:normal
irc.twistednet.org:6697:TwistedNet:ssl
irc.umbrellanet.org:6667:UmbrellaNet:normal
eu.undernet.org:6667:Undernet:normal
irc.undernet.org:6667:Undernet:normal
chat.unibg.net:6667:UniBG:normal
irc.unifiedchat.net:6667:UnifiedChat:normal
irc.unifiedchat.net:6697:UnifiedChat:ssl
irc.virtualife.com.br:6667:VirtuaLife:normal
irc.virtualife.org:6667:VirtuaLife:normal
irc.w3.org:6667:w3.org:normal
irc.w3.org:6697:w3.org:ssl
irc.wetfish.net:6697:WetFish:ssl
irc.whatnet.org:6667:WhatNET:normal
irc.wnet.tk:6667:WNet:normal
irc.wnet.tk:6697:WNet:ssl
irc.worldirc.org:6667:WorldIRC:normal
eu.worldirc.org:6667:WorldIRC:normal
irc.xertion.org:6667:Xertion:normal
irc.xertion.org:6697:Xertion:ssl
irc.zenet.org:6667:ZEnet:normal
irc.zeronode.net:6667:ZeroNode:normal"""
